# CUSTOM PLAYBOOK #1 — Invoke 2 modules to automatically update 2 types of servers.

---
# Task 1
- name: Update web servers
  hosts: webservers
  become: true

  tasks:
    - name: Ensure apache is at the latest version
      ansible.builtin.package:
        name: httpd
        state: latest
    
    - name: Write the apache config file from template with mode='0644' and root
      ansible.builtin.template:
        src: httpd.j2
        dest: /etc/httpd/conf/httpd.conf
        mode: '0644'
        owner: root
        group: root
    
    



# Task 2
- name: Update db servers
  hosts: databases
  become: true

  tasks:
    - name: Ensure postgresql is at the latest version

    - name: Ensure that postgresql is started
